[package]
name = "traqio"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
argon2rs = "0.2.5"
csv = "1.3.1"
futures = "0.3.31"
hex = "0.4.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
uuid = { version = "1", features = ["v4"] }
